<a target="_blank" href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/vci/vci_functions_demo.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Mục lục

# I. Cài đặt

## Cài đặt thư viện

In [ ]:
!pip install -U vnstock

## Nạp thư viện lần đầu

> Bạn có thể nạp toàn bộ các module của thư viện vào môi trường làm việc nếu chưa biết rõ mình cần gì hoặc chọn từng module riêng biệt để nạp vào khi đã quen thuộc.

In [69]:
from vnstock.explorer.vci import Listing, Quote, Company, Finance, Trading

# II. Truy xuất dữ liệu - CK Việt Nam

## Listing: Liệt kê danh sách chứng khoán

In [4]:
listing = Listing()

### Danh sách tất cả mã CK niêm yết (đơn giản)

In [ ]:
# VCI là nguồn dữ liệu từ CK Vietcap bên cạnh nguồn từ TCBS
listing.all_symbols()

     symbol                                         organ_name
0       YTC  Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1       YEG                     Công ty Cổ phần Tập đoàn Yeah1
2       YBM     Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3       YBC      Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4       XPH                    Công ty Cổ phần Xà phòng Hà Nội
...     ...                                                ...
1704    AAS            Công ty Cổ phần Chứng khoán SmartInvest
1705    AAM                    Công ty Cổ Phần Thủy Sản MeKong
1706    AAH                           Công ty Cổ phần Hợp Nhất
1707    AAA                  Công ty Cổ phần Nhựa An Phát Xanh
1708    A32                                 Công ty Cổ phần 32

[1709 rows x 2 columns]

In [ ]:
# Xuất dữ liệu ra file csv
listing.all_symbols().to_csv('assets/data/all_symbols.csv', index=False)

### Liệt kê mã CP theo sàn (đầy đủ)

In [6]:
# Dữ liệu bao gồm tất cả các mã không kể đang niêm yết hay không
listing.symbols_by_exchange()

,symbol,exchange,type,organ_short_name,organ_name
0,YTC,UPCOM,STOCK,XNK Y tế TP.HCM,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1,YEG,HSX,STOCK,Tập đoàn Yeah1,Công ty Cổ phần Tập đoàn Yeah1
2,YBM,HSX,STOCK,Khoáng sản CN Yên Bái,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3,YBC,UPCOM,STOCK,Xi măng và Khoáng sản Yên Bái,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4,XPH,UPCOM,STOCK,Xà phòng Hà Nội,Công ty Cổ phần Xà phòng Hà Nội
...,...,...,...,...,...
2753,AAS,UPCOM,STOCK,Chứng khoán SmartInvest,Công ty Cổ phần Chứng khoán SmartInvest
2754,AAM,HSX,STOCK,Thủy sản Mekong,Công ty Cổ Phần Thủy Sản MeKong
2755,AAH,UPCOM,STOCK,Than Hợp Nhất,Công ty Cổ phần Hợp Nhất
2756,AAA,HSX,STOCK,An Phát Bioplastics,Công ty Cổ phần Nhựa An Phát Xanh
2757,A32,UPCOM,STOCK,Công ty 32,Công ty Cổ phần 32

In [75]:
# Xuất dữ liệu ra file csv
listing.symbols_by_exchange().to_csv('assets/data/symbols_by_exchange.csv', index=False)

### Liệt kê mã CP theo ngành icb

In [7]:
listing.symbols_by_industries()

,symbol,organ_name,icb_name3,icb_name2,icb_name4,com_type_code,icb_code1,icb_code2,icb_code3,icb_code4
0,BMK,Công ty Cổ Phần Kỹ thuật Nhiệt Mèo Đen,Xây dựng và Vật liệu,Xây dựng và Vật liệu,Vật liệu xây dựng & Nội thất,CT,2000,2300,2350,2353
1,LPT,Công ty Cổ phần Thương mại và Sản xuất Lập Phư...,Tư vấn & Hỗ trợ Kinh doanh,Hàng & Dịch vụ Công nghiệp,Đào tạo & Việc làm,CT,2000,2700,2790,2793
2,ACB,Ngân hàng Thương mại Cổ phần Á Châu,Ngân hàng,Ngân hàng,Ngân hàng,NH,8301,8300,8350,8355
3,CAG,Công ty Cổ phần Cảng An Giang,Vận tải,Hàng & Dịch vụ Công nghiệp,"Kho bãi, hậu cần và bảo dưỡng",CT,2000,2700,2770,2777
4,AGR,Công ty Cổ phần Chứng khoán AGRIBANK,Dịch vụ tài chính,Dịch vụ tài chính,Môi giới chứng khoán,CK,8000,8700,8770,8777
...,...,...,...,...,...,...,...,...,...,...
1587,XPH,Công ty Cổ phần Xà phòng Hà Nội,Hàng cá nhân,Hàng cá nhân & Gia dụng,Hàng cá nhân,CT,3000,3700,3760,3767
1588,XHC,Công ty Cổ phần Xuân Hòa Việt Nam,Hàng gia dụng,Hàng cá nhân & Gia dụng,Thiết bị gia dụng,CT,3000,3700,3720,3726
1589,YBC,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái,Xây dựng và Vật liệu,Xây dựng và Vật liệu,Vật liệu xây dựng & Nội thất,CT,2000,2300,2350,2353
1590,XMP,Công ty Cổ phần Thủy điện Xuân Minh,Sản xuất & Phân phối Điện,"Điện, nước & xăng dầu khí đốt",Sản xuất & Phân phối Điện,CT,7000,7500,7530,7535
1591,YBM,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái,Khai khoáng,Tài nguyên Cơ bản,Khai khoáng,CT,1000,1700,1770,1775

In [78]:
# Xuất dữ liệu ra file csv
listing.symbols_by_industries().to_csv('assets/data/symbols_by_industries.csv', index=False)

### Danh sách cổ phiếu theo nhóm

In [8]:
# Liệt kê tất cả mã chứng khoán theo nhóm phân loại. Ví dụ HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (mã chỉ số hợp đồng tương lai), CW (chứng quyền)
listing.symbols_by_group('VN30')

0     ACB
1     BCM
2     BID
3     BVH
4     CTG
5     FPT
6     GAS
7     GVR
8     HDB
9     HPG
10    LPB
11    MBB
12    MSN
13    MWG
14    PLX
15    SAB
16    SHB
17    SSB
18    SSI
19    STB
20    TCB
21    TPB
22    VCB
23    VHM
24    VIB
25    VIC
26    VJC
27    VNM
28    VPB
29    VRE
Name: symbol, dtype: object

In [77]:
# Xuất dữ liệu ra file csv
listing.symbols_by_group('VN30').to_csv('assets/data/vn30_symbols.csv', index=False)

### Danh sách mã ngành theo mã icb

In [9]:
listing.industries_icb()

,icb_name,en_icb_name,icb_code,level
0,Sản xuất Dầu khí,Oil & Gas Producers,0530,3
1,"Thiết bị, Dịch vụ và Phân phối Dầu khí","Oil Equipment, Services & Distribution",0570,3
2,Hóa chất,Chemicals,1350,3
3,Lâm nghiệp và Giấy,Forestry & Paper,1730,3
4,Kim loại,Industrial Metals & Mining,1750,3
...,...,...,...,...
150,Viễn thông,Telecommunications,6000,1
151,Tiện ích Cộng đồng,Utilities,7000,1
152,Tài chính,Financials,8000,1
153,Ngân hàng,Banks,8301,1
154,Công nghệ Thông tin,Technology,9000,1

In [79]:
# Xuất dữ liệu ra file csv
listing.industries_icb().to_csv('assets/data/industries_icb.csv', index=False)

## Quote: Giá chứng khoán

> Không giống như khi sử dụng nhóm hàm tổng hợp `Vnstock` như cổng giao tiếp với phần mềm, bạn cần định nghĩa thông tin `symbol` tại lớp `Quote` khi nạp chương trình và không thể sử dụng tham số `symbol` trong các hàm thành phần. Để truy vấn các mã chứng khoán khác nhau, bạn cần khai báo tại `Quote`

In [44]:
# # Lấy thông tin chi tiết của một mã cổ phiếu, ETF
quote = Quote(symbol='FPT')

In [ ]:
# Lấy thông tin mã HĐTL
quote = Quote(symbol='VN30F1M')
# hoặc
# quote = Quote(symbol='VN30F2506')

In [42]:
# Lấy thông tin mã chỉ số
quote = Quote(symbol='VNINDEX')

In [ ]:
# Lấy thông tin mã chứng quyền (CW)
quote = Quote(symbol='CFPT2314')

In [40]:
# Thông tin trái phiếu niêm yết
quote = Quote(symbol='CII424002')

#### Giá lịch sử

In [38]:
df = quote.history(start='2024-01-01', end='2025-03-19', interval='1D')
df

          time    open    high     low   close  volume
0   2024-04-11  120.00  139.50  120.00  135.00  186701
1   2024-04-12  132.50  135.10  125.00  130.20  111161
2   2024-04-15  130.20  130.30  123.00  123.50   61607
3   2024-04-16  123.00  123.00  117.00  117.00   31563
4   2024-04-17  114.20  119.00  110.90  117.00   11721
..         ...     ...     ...     ...     ...     ...
227 2025-03-13  125.90  125.90  125.90  125.90      10
228 2025-03-14  125.00  126.00  125.00  126.00    2000
229 2025-03-17  126.00  127.00  126.00  127.00    6014
230 2025-03-18  127.01  128.50  127.01  128.00    1780
231 2025-03-19  127.01  127.01  127.01  127.01   83350

[232 rows x 6 columns]

In [31]:
# Tất cả dataframe dữ liệu sẽ được gán thuộc tính tên và loại tài sản tương ứng
print(f'Mã chứng khoán: {df.name}')
print(f'Loại tài sản: {df.category}')

Mã chứng khoán: VN30F2506
Loại tài sản: derivative

#### Intraday: dữ liệu khớp lệnh

In [45]:
# Dữ liệu khớp lệnh trong ngày giao dịch realtime hoặc ngày gần nhất (ngoài giờ giao dịch)
quote.intraday(page_size=10_000, show_log=False)

                          time     price  volume match_type         id
0    2025-04-04 10:32:34+07:00  108800.0     200        Buy  285392781
1    2025-04-04 10:32:34+07:00  108800.0     500        Buy  285392782
2    2025-04-04 10:32:39+07:00  108800.0     200        Buy  285392931
3    2025-04-04 10:32:40+07:00  108800.0     400        Buy  285392993
4    2025-04-04 10:32:41+07:00  108800.0     200        Buy  285393010
...                        ...       ...     ...        ...        ...
9995 2025-04-04 14:29:57+07:00  113900.0     100        Buy  285744581
9996 2025-04-04 14:29:58+07:00  113900.0     100        Buy  285744625
9997 2025-04-04 14:29:58+07:00  113900.0     200        Buy  285744721
9998 2025-04-04 14:29:59+07:00  113900.0     100        Buy  285744754
9999 2025-04-04 14:45:01+07:00  113000.0  520100        ATC  285746170

[10000 rows x 5 columns]

In [46]:
# Bước giá và khối lượng giao dịch: realtime
quote.price_depth()

     price acc_volume acc_buy_volume acc_sell_volume acc_undefined_volume
0   113900        500            500               0                    0
1   113800      11700           8600            3100                    0
2   113700       8600           5400            3200                    0
3   113600      58800           5800           53000                    0
4   113500     245200         204400           40800                    0
..     ...        ...            ...             ...                  ...
79  106000     767800         299700          468100                    0
80  105900     124800          59300           65500                    0
81  105800     118100          82900           35200                    0
82  105700     375200         178300          196900                    0
83  105600    7282900        4692600          772900              1817400

[84 rows x 5 columns]

## Trading: Giao dịch

In [47]:
from vnstock.explorer.vci import Trading
trading = Trading()

### Bảng giá

In [49]:
trading.price_board(['ACB'])

  listing                                                                 \
   symbol ceiling  floor ref_price stock_type exchange last_trading_date
0     ACB   25800  22500     24150      STOCK      HSX

                                ...     bid_ask                           \
  listed_share   type       id  ... bid_2_price bid_2_volume bid_3_price
0   4466657912  STOCK  8424512  ...       23700        16700       23650

                                                                              \
  bid_3_volume ask_1_price ask_1_volume ask_2_price ask_2_volume ask_3_price
0         3600       23800       178100       23850       248200       23900


  ask_3_volume
0       263500

[1 rows x 41 columns]

In [57]:
trading.price_board(['VCB','ACB','TCB','BID'], flatten_columns=True, drop_levels=[0]).T # Bỏ .T để xoay trở lại đúng kiểu hiển thị bảng giá

,0,1,2,3
symbol,VCB,ACB,TCB,BID
ceiling,64500,25800,27750,38500
floor,56100,22500,24150,33500
ref_price,60300,24150,25950,36000
stock_type,STOCK,STOCK,STOCK,STOCK
exchange,HSX,HSX,HSX,HSX
last_trading_date,,,,
listed_share,8355691435,4466657912,7064851739,6897515268
type,STOCK,STOCK,STOCK,STOCK
id,8424561,8424512,8424683,8424583
organ_name,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...,Ngân hàng Thương mại Cổ phần Á Châu,Ngân hàng Thương mại Cổ phần Kỹ thương Việt Nam,Ngân hàng Thương mại Cổ phần Đầu tư và Phát tr...
prior_close_price,60300,24150,25950,36000
benefit,,,,
trading_date,2025-04-04,2025-04-04,2025-04-04,2025-04-04
match_price,60000,23800,25700,36000
match_vol,156700,1499900,1008700,284200
accumulated_volume,11887700,72249400,56795800,6883200
accumulated_value,686170,1656708,1413050,236970
avg_match_price,57721.005745,22930.404958,24879.480525,34427.301255
highest,60000,23800,25750,36000
lowest,56200,22500,24150,33550
match_type,unknown,unknown,unknown,unknown
foreign_sell_volume,9370459,20683732,13418345,1053838
foreign_buy_volume,2631500,67000,5702200,873889
current_room,405888864,0,0,868431244
total_room,1676727378,1339997373,1590552461,2106408575
total_accumulated_value,686170.69,1656708.02,1413050.65,236970.725
total_accumulated_volume,118877,722494,567958,68832
reference_price,60300,24150,25950,36000
bid_1_price,59900,23750,25700,35950
bid_1_volume,100,5900,159600,200
bid_2_price,59500,23700,25650,35500
bid_2_volume,700,16700,105400,16900
bid_3_price,59400,23650,25600,35450
bid_3_volume,500,3600,77200,42500
ask_1_price,60000,23800,25750,36000
ask_1_volume,1391700,178100,51400,90600
ask_2_price,60100,23850,25800,36050
ask_2_volume,100,248200,714100,1000
ask_3_price,60200,23900,25850,36150
ask_3_volume,200,263500,16000,12000

## Company: Thông tin công ty

In [ ]:
# # Khởi tạo đối tượng
# from vnstock import Vnstock
# company = Vnstock().stock(symbol='ACB', source='VCI').company

# hoặc
from vnstock.explorer.vci import Company
company = Company('ACB')

Loại bỏ đoạn mã `.head()` để xem toàn bộ dữ liệu thay vì chỉ lấy 5 dòng đầu tiên.

#### Hồ sơ

In [ ]:
company.overview()

,symbol,id,issue_share,history,company_profile,icb_name3,icb_name2,icb_name4,financial_ratio_issue_share,charter_capital
0,ACB,67505,4466657912,- Ngày 24/04/1993: Ngân hàng Thương mại Cổ ph...,Ngân hàng Thương mại Cổ phần Á Châu (ACB) được...,Ngân hàng,Ngân hàng,Ngân hàng,4466657900,44666579120000

#### Cổ đông

In [ ]:
company.shareholders()

,id,share_holder,quantity,share_own_percent,update_date
0,76868950,Vietnam Enterprise Investments Limited,212880184,5.480880e-02,2024-09-13
1,76863823,Sather Gate Investments Limited,193907186,4.990000e-02,2024-05-15
2,76861604,Phạm Thị Thu Hà,285000,4.990000e-02,2016-05-20
3,76845328,Estes Investments Limited,83010435,4.990000e-02,2024-05-15
4,76865801,Trần Hùng Huy,153062159,3.940000e-02,2025-01-24
...,...,...,...,...,...
81,76858006,Nguyễn Thị Tuyết Vân,88722,1.730000e-05,2025-01-24
82,76863346,Quỹ Đầu tư Cổ phiếu Năng động Bảo Việt,22065,1.327000e-05,2025-02-03
83,76843608,Đinh Thị Hoa,67200,1.200000e-05,2025-01-24
84,76839576,Công ty Cổ phần Chứng khoán Thiên Việt,5285,1.500000e-06,2022-07-25
85,76853275,Nguyễn Hồng Nga,2008,7.000000e-07,2022-08-31

#### Công ty con

In [ ]:
company.subsidiaries()

,id,sub_organ_code,ownership_percent,organ_name,type
0,21757755,ACBA,1,Công Ty TNHH Quản Lý Nợ Và Khai Thác Tài Sản N...,công ty con
1,21757756,ACBL,1,Công Ty TNHH Một Thành Viên Cho Thuê Tài Chính...,công ty con
2,21757757,ACBS,1,Công ty TNHH Chứng khoán ACB,công ty con
0,21757759,ACBD,None,CÔNG TY CỔ PHẦN DỊCH VỤ BẢO VỆ NGÂN HÀNG Á CHÂU,công ty liên kết
1,21757758,SGGS,None,Công ty Cổ phần Sài Gòn Kim hoàn ACB- SJC,công ty liên kết

#### Công ty liên kết

In [ ]:
# Phương thức này không có trong nguồn TCBS
company.affiliate()

,id,sub_organ_code,organ_name,ownership_percent
0,21757759,ACBD,CÔNG TY CỔ PHẦN DỊCH VỤ BẢO VỆ NGÂN HÀNG Á CHÂU,None
1,21757758,SGGS,Công ty Cổ phần Sài Gòn Kim hoàn ACB- SJC,None

#### Lãnh đạo

In [ ]:
company.officers(filter_by='working').head() # filter_by='all' hoặc 'working' hoặc 'resigned'

,id,officer_name,officer_position,position_short_name,update_date,officer_own_percent,quantity
0,6,Trần Hùng Huy,Chủ tịch Hội đồng Quản trị,Chủ tịch HĐQT,2025-01-24,0.0394,153062159
1,7,Đặng Thu Thủy,Thành viên Hội đồng Quản trị,TV HĐQT,2025-01-24,0.0137,53350036
2,11,Đặng Phú Vinh,Giám đốc khối,GĐ Khối,2025-01-24,0.0042,16454507
3,13,Đỗ Minh Toàn,Tổng Giám đốc,TGĐ,2025-01-24,0.0008,3202886
4,8,Nguyễn Thành Long,Phó Chủ tịch Hội đồng Quản trị,Phó Chủ tịch HĐQT,2025-01-24,0.0004,1647067

#### Tin tức

In [ ]:
company.news().head(3)

,id,news_title,news_sub_title,friendly_sub_title,news_image_url,news_source_link,created_at,public_date,updated_at,lang_code,news_id,news_short_content,news_full_content,close_price,ref_price,floor,ceiling,price_change_pct
0,7009867,ACB: Báo cáo kết quả giao dịch cổ phiếu của t...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/Modules/Cms/Web/LoadArticle...,None,1742998200000,None,vi,11505980,ACB: Báo cáo kết quả giao dịch cổ phiếu của t...,<p>Công ty TNHH MTV Nhật Quân HQ báo cáo kết q...,26150,26300,24500,28100,-0.005703
1,7001147,ACB: Báo cáo thường niên năm 2024,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/Modules/Cms/Web/LoadArticle...,None,1742901180000,None,vi,11504387,ACB: Báo cáo thường niên năm 2024,<p>Ngân hàng Thương mại Cổ phần Á Châu công bố...,26300,26350,24550,28150,-0.001898
2,6944486,ACB: Công ty TNHH MTV Nhật Quân HQ đăng ký bá...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/Modules/Cms/Web/LoadArticle...,None,1742315220000,None,vi,11497368,ACB: Thông báo giao dịch cổ phiếu của tổ chức...,<p>Công ty TNHH MTV Nhật Quân HQ thông báo gia...,26300,26200,24400,28000,0.003817

#### Sự kiện

In [ ]:
company.events().head(3)

,id,event_title,en__event_title,public_date,issue_date,source_url,event_list_code,ratio,value,record_date,exright_date,event_list_name,en__event_list_name
0,23057391,ACB - Trả cổ tức Cả năm năm 2022 bằng tiền 100...,ACB - Pay cash dividend 2022 - Year at VND 100...,2023-05-25,2023-06-12,http://fiinpro.com/News/Detail/10793461?lang=v...,DIV,0.1,1000.0,2023-06-02,2023-06-01,Trả cổ tức bằng tiền mặt,Cash Dividend
1,38768795,ACB - Trả cổ tức Cả năm năm 2023 bằng tiền 100...,ACB - Pay cash dividend 2023 - Year at VND 100...,2024-05-24,2024-06-13,http://fiinpro.com/News/Detail/11196089?lang=v...,DIV,0.1,1000.0,2024-06-03,2024-05-31,Trả cổ tức bằng tiền mặt,Cash Dividend
2,18129,Phát hành cổ phiếu,,2010-11-18,2010-11-30,,ISS,NaN,NaN,2010-11-30,2010-11-26,Phát hành cổ phiếu,Share Issue

#### Báo cáo phân tích

In [ ]:
company.reports()

,date,description,link,name
0,2025-01-22T00:00:00Z,Ngân hàng Thương Mại Cổ Phần Á Châu (ACB) đã c...,https://www.vietcap.com.vn/trung-tam-phan-tich...,ACB - Tập trung vào tăng trưởng tín dụng hơn t...
1,2024-10-24T00:00:00Z,Ngân hàng TMCP Á Châu (ACB) công bố KQKD 9 thá...,https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB – NOII thấp hơn dự kiến, ảnh hưởng tiêu cự..."
2,2024-09-09T00:00:00Z,- Chúng tôi tiếp tục duy trì giá mục tiêu đối ...,https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB [MUA +35,0%] - Tăng dự báo tăng trưởng tín..."
3,2024-07-23T00:00:00Z,ACB đã công bố KQKD nửa đầu năm 2024 với thu n...,https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB - Tín dụng tăng trưởng mạnh, chất lượng tà..."
4,2024-06-04T00:00:00Z,"- Chúng tôi điều chỉnh tăng 8,6% giá mục tiêu ...",https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB [MUA +33,7%] - NIM tương đối đi ngang tron..."
5,2024-04-26T00:00:00Z,"ACB đã công bố KQKD quý 1/2024 với TOI đạt 8,2...",https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB – NOII thấp, chất lượng tài sản được duy t..."
6,2024-04-04T00:00:00Z,Chúng tôi đã tham dự ĐHCĐ của Ngân hàng TMCP Á...,https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB - Tín dụng tăng trưởng mạnh, duy trì tỷ lệ..."
7,2024-03-05T00:00:00Z,"- Chúng tôi điều chỉnh tăng 7,6% giá mục tiêu ...",https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB [MUA +26,3%] - Tăng trưởng ổn định nhờ cho..."
8,2024-01-26T00:00:00Z,"ACB công bố KQKD năm 2023 với TOI đạt 32,7 ngh...",https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB – Tăng trưởng tín dụng vượt kỳ vọng, lợi n..."
9,2023-11-15T00:00:00Z,- Chúng tôi điều chỉnh tăng giá mục tiêu cho N...,https://www.vietcap.com.vn/trung-tam-phan-tich...,"ACB [MUA +42,7%] - Chiến lược rủi ro thấp mang..."

#### Tình hình tài chính

In [ ]:
company.ratio_summary()

,symbol,year_report,length_report,update_date,revenue,revenue_growth,net_profit,net_profit_growth,ebit_margin,roe,...,rtq4,charter_capital_ratio,rtq10,dividend,ebitda,ebit,le,de,ccc,rtq17
0,ACB,2024,5,1741199572843,50902749000000,-0.027586,16789768000000,0.046435,0,0.217459,...,0,1.868549,0,0,0,0,0,0,None,0

#### Thống kê giao dịch

In [ ]:
company.trading_stats()

,symbol,exchange,ev,ceiling,floor,ref_price,open,match_price,close_price,price_change,...,high_price_1y,low_price_1y,pct_low_change_1y,pct_high_change_1y,foreign_volume,foreign_room,avg_match_volume_2w,foreign_holding_room,current_holding_ratio,max_holding_ratio
0,ACB,HOSE,116803104085000,28100,24500,26300,26300,26150,26150,-150,...,26800,22218,0.170337,-0.018762,0,1339997373,6998548,1339997373,0.3,0.3

### TCBS

In [ ]:
from vnstock import Vnstock

company = Vnstock().stock(symbol='VCB', source='TCBS').company

2025-03-27 22:37:18 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

#### Tổng quan

In [ ]:
company.overview()

,symbol,exchange,industry,company_type,no_shareholders,foreign_percent,outstanding_share,issue_share,established_year,no_employees,stock_rating,delta_in_week,delta_in_month,delta_in_year,short_name,website,industry_id,industry_id_v2
0,VCB,HOSE,Ngân hàng,NH,25183,0.227,8355.7,5589.1,2008,24306,2.6,-0.019,0.045,-0.016,Vietcombank,https://vietcombank.com.vn,289,8355

#### Hồ sơ

In [ ]:
company.profile()

,symbol,company_name,company_profile,history_dev,company_promise,business_risk,key_developments,business_strategies
0,VCB,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...,Ngân hàng Thương mại Cổ phần Ngoại thương Việ...,Ngày 30/10/1962: Ngân hàng Ngoại thương Việt...,None,Rủi ro địa chính trị và nguy cơ chiến tranh ...,Dịch vụ tài khoản Dịch vụ huy động vốn (tiền...,"Ngân hàng số 1 tại Việt Nam, một trong 100 ng..."

#### Cổ đông

In [ ]:
company.shareholders()

                  share_holder  share_own_percent
0  Ngân Hàng Nhà Nước Việt Nam             0.7480
1          Mizuho Bank Limited             0.1500
2                         Khác             0.0207

#### Giao dịch nội bộ

In [ ]:
company.insider_deals().head(3)

,deal_announce_date,deal_method,deal_action,deal_quantity,deal_price,deal_ratio
0,2025-02-20,Cổ đông nội bộ,Mua,10000.0,61338.0,0.068
1,2023-12-21,Cổ đông nội bộ,Mua,5000.0,54114.0,0.210
2,2020-12-30,Cổ đông sáng lập,Bán,-2523.0,42927.0,0.526

#### Công ty con, liên kết

In [ ]:
company.subsidiaries().head()

                                    sub_company_name  sub_own_percent
0  Công ty TNHH Chứng khoán Ngân hàng Thương mại ...              1.0
1  Công Ty TNHH Một Thành Viên Kiều Hối Ngân Hàng...              1.0
2  Công ty TNHH MTV Cho Thuê Tài Chính Ngân Hàng ...              1.0
3      Công ty TNHH Tài Chính Việt Nam Tại Hồng Kông              1.0
4   Ngân Hàng TNHH MTV Ngoại Thương Việt Nam Tại Lào              1.0

#### Ban lãnh đạo

In [ ]:
company.officers().head()

         officer_name              officer_position  officer_own_percent
3   Nguyễn Danh Lương  Thành viên Hội đồng Quản trị                  0.0
10     Lê Thị Kim Nga  Thành viên Hội đồng Quản trị                  0.0
15         Lê Thị Hoa  Thành viên Hội đồng Quản trị                  0.0
12   Đỗ Thị Mai Hương      Thành viên Ban kiểm soát                  0.0
5   Nguyễn Danh Lương   Phụ trách Công bố thông tin                  0.0

#### Sự kiện

In [ ]:
company.events().head()

The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.

,rsi,rs,id,price,price_change,price_change_ratio,price_change_ratio_1m,event_name,event_code,notify_date,exer_date,reg_final_date,exer_right_date,event_desc
0,73.4,58.0,2584165,66700.0,1950.0,0.030,0.090,VCB - Tổ chức ĐHĐCĐ thường niên 2025,AGME,2025-03-12,2025-04-26,2025-03-26,2025-03-25,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
1,54.0,37.0,2583928,62542.0,334.0,0.005,0.006,"VCB - Phát hành cổ phiếu trả cổ tức tỷ lệ 49,5%",ISS,2025-03-06,2025-03-12,2025-03-13,2025-03-12,Ngân hàng Thương mại Cổ phần Ngoại thương Việt...
2,46.6,29.0,2582516,61338.0,0.0,0.000,0.000,VCB - Kết quả giao dịch nội bộ/CĐL,DDALL,2025-02-20,2025-02-19,1753-01-01,1753-01-01,- Cá nhân/Tổ chức thực hiện giao dịch: Phùng N...
3,55.4,44.0,2581736,62208.0,67.0,0.001,0.008,VCB - Thông báo đăng ký giao dịch nội bộ/CĐL,DDALL,2025-02-07,2025-03-12,1753-01-01,1753-01-01,- Cá nhân/Tổ chức thực hiện giao dịch: Phùng N...
4,52.8,52.0,2580835,61940.0,67.0,0.001,0.005,VCB - BCTC Quý 4/2024,KQQY,2025-01-24,2025-01-24,1753-01-01,1753-01-01,VCB - BCTC Quý 4/2024

#### Tin tức

In [ ]:
company.news().head()

,rsi,rs,price,price_change,price_change_ratio,price_change_ratio_1m,id,title,source,publish_date
0,NaN,NaN,NaN,NaN,NaN,NaN,11507583,VCB: Báo cáo kết quả phát hành cổ phiếu để tr...,TCBS,2025-03-27 15:04:00
1,NaN,NaN,NaN,NaN,NaN,NaN,11507578,VCB: Thông báo thay đổi số lượng cổ phiếu có ...,TCBS,2025-03-27 14:56:00
2,70.4,70.0,66500.0,-300.0,-0.004,0.084,11498692,VCB: HĐQT phê duyệt điều chỉnh giới hạn tín d...,TCBS,2025-03-19 15:31:00
3,70.4,70.0,66500.0,-300.0,-0.004,0.084,11498688,VCB: HĐQT phê duyệt giới hạn tín dụng đối với...,TCBS,2025-03-19 15:30:00
4,68.2,63.0,66000.0,500.0,0.008,0.077,11494381,VCB: Nghị quyết HĐQT về việc phê duyệt giới h...,TCBS,2025-03-14 17:15:00

#### Cổ tức

In [ ]:
company.dividends().head()

  exercise_date  cash_year  cash_dividend_percentage issue_method
0    2025-03-12       2025                     0.495        share
1    2023-07-25       2023                     0.181        share
2    2021-12-22       2022                     0.276        share
3    2021-12-22       2020                     0.120         cash
4    2020-12-21       2019                     0.080         cash

## Finance: Báo cáo tài chính

In [58]:
from vnstock.explorer.vci import Finance
fin =  Finance(symbol='VCI')

### Bảng cân đối kế toán

In [59]:
fin.balance_sheet(period='year', lang='vi', dropna=True)

,CP,Năm,TÀI SẢN NGẮN HẠN (đồng),Tiền và tương đương tiền (đồng),Giá trị thuần đầu tư ngắn hạn (đồng),Các khoản phải thu ngắn hạn (đồng),Hàng tồn kho ròng,Tài sản lưu động khác,TÀI SẢN DÀI HẠN (đồng),Tài sản cố định (đồng),...,"Hàng tồn kho, ròng (đồng)",Tài sản lưu động khác (đồng),Cổ phiếu phổ thông (đồng),Vốn góp của chủ sở hữu (đồng),Vay và nợ thuê tài chính dài hạn (đồng),Người mua trả tiền trước ngắn hạn (đồng),Vay và nợ thuê tài chính ngắn hạn (đồng),Trả trước dài hạn (đồng),Tài sản dài hạn khác (đồng),LỢI ÍCH CỦA CỔ ĐÔNG THIỂU SỐ
0,VCI,2024,26491835561026,4743771932745,21072524575199,506858248065,0,168680805017,100288918214,37268698440,...,0,135374861200,7.180995e+12,7180994800000,0,2743133560,12573864000000,6238956911,0,0.000000e+00
1,VCI,2023,17174448616966,787897819240,15097165308797,1094491429414,0,194894059515,80686039559,23425609453,...,0,147257185100,4.375000e+12,4375000000000,0,378319774,8979275000000,7943878800,0,0.000000e+00
2,VCI,2022,14157693071824,3423501614803,10562264962864,120085485886,0,51841008271,85058244998,23496558588,...,0,46136989800,4.354999e+12,4354999010000,0,221000000,6326207142857,13290531600,0,0.000000e+00
3,VCI,2021,16568965942558,1131748599533,14998113044339,285206345277,0,153897953409,67299004559,13155825424,...,0,150714917648,3.330000e+12,3330000000000,0,52551076244,6362680000000,10702485700,0,0.000000e+00
4,VCI,2020,8312170798945,642512983590,6697916243107,221798617565,0,97527648804,70234326495,14384201512,...,0,91333803000,1.656000e+12,1656000000000,0,7971369863,2696130000000,12950546970,0,0.000000e+00
5,VCI,2019,7173102515011,794511762602,5817229478552,747087592357,0,165433739031,69857713462,9907318916,...,0,164204396000,1.644000e+12,1644000000000,0,210000000,1450980000000,17085900679,0,0.000000e+00
6,VCI,2018,6430493843962,1144361568890,5252959790479,30487868695,0,2684615898,79502079245,18226354386,...,0,0,1.629999e+12,1629998900000,0,126324890101,984860000000,25494063880,0,0.000000e+00
7,VCI,2017,6342806740944,486703202803,5709256554482,28256236703,0,118590746956,59205004260,25326131092,...,0,116156411000,1.200000e+12,1200000000000,0,462392057000,1434460418662,2171535344,0,0.000000e+00
8,VCI,2016,3075625891871,545670784533,2481417250820,44869461531,0,7607339062,34921874969,9489824544,...,0,1335936000,1.032000e+12,1032000000000,0,571264678998,627508000000,4433448206,0,7.721605e+10
9,VCI,2015,2423478575254,158181741192,2092718191471,78849205458,0,92517941380,39867670505,14899441202,...,0,87885991500,5.000000e+11,500000000000,0,799974087998,535500000000,9817929938,0,7.475699e+10
10,VCI,2014,2707101348631,618777857754,1939716412996,141064801745,14179400,7528096736,63219168401,18390029859,...,14179400,3095401526,5.000000e+11,500000000000,0,840646942003,266511750000,14560154043,14160000000,7.604128e+10
11,VCI,2013,2090711345801,312645301464,1659030664666,117641213076,16677400,1377489195,41576018914,11027268785,...,16677400,87777500,0.000000e+00,398400000000,0,470366997300,648400000000,16231644217,0,0.000000e+00
12,VCI,2011,1795452129469,111616718751,1059922610501,614818783909,12320284,9081696024,622201775573,7612776214,...,12320284,6609715987,3.780000e+11,378000000000,500000000000,121749992655,582426780000,0,594640525000,0.000000e+00

In [60]:
fin.balance_sheet(period='quarter', lang='en', dropna=True).head()

,ticker,yearReport,lengthReport,CURRENT ASSETS (Bn. VND),Cash and cash equivalents (Bn. VND),Short-term investments (Bn. VND),Accounts receivable (Bn. VND),Net Inventories,Other current assets,LONG-TERM ASSETS (Bn. VND),...,Other current assets (Bn. VND),Common shares (Bn. VND),Paid-in capital (Bn. VND),Long-term borrowings (Bn. VND),Advances from customers (Bn. VND),Short-term borrowings (Bn. VND),Long-term prepayments (Bn. VND),Other long-term assets (Bn. VND),Goodwill,MINORITY INTERESTS
0,VCI,2024,4,26491835561026,4743771932745,21072524575199,506858248065,0,168680805017,100288918214,...,135374861200,7.180995e+12,7180994800000,0,2743133560,12573864000000,6238956911,0,0,0.0
1,VCI,2024,3,20322217963459,2543516547760,17408880681428,235746508338,0,134074225933,92945134178,...,122374861200,5.744695e+12,5744694800000,0,4431803623,10832654000000,7503462322,0,0,0.0
2,VCI,2024,2,23009916452730,3903157759657,17775135464006,931122579216,0,400500649851,95455335905,...,372374861200,4.419000e+12,4419000000000,0,1753351687,12392104000000,8879984392,0,0,0.0
3,VCI,2024,1,19458498860847,1040594399692,17454154906730,702530886335,0,261218668090,86105265555,...,227872273100,4.375000e+12,4375000000000,0,1083817322,10239557000000,9017164629,0,0,0.0
4,VCI,2023,4,17174448616966,787897819240,15097165308797,1094491429414,0,194894059515,80686039559,...,147257185100,4.375000e+12,4375000000000,0,378319774,8979275000000,7943878800,0,0,0.0

### Báo cáo lãi lỗ

In [61]:
fin.income_statement(period='year', lang='vi', dropna=True).head()

,CP,Năm,Doanh thu (đồng),Tăng trưởng doanh thu (%),Lợi nhuận sau thuế của Cổ đông công ty mẹ (đồng),Tăng trưởng lợi nhuận (%),Doanh thu thuần,Giá vốn hàng bán,Lãi gộp,Thu nhập tài chính,...,Lợi nhuận khác,LN trước thuế,Chi phí thuế TNDN hiện hành,Chi phí thuế TNDN hoãn lại,Lợi nhuận thuần,Cổ đông thiểu số,Cổ đông của Công ty mẹ,Doanh thu bán hàng và cung cấp dịch vụ,Thu nhập khác,Thu nhập/Chi phí khác
0,VCI,2024,3695525335470,0.494675,910692113293,0.851359,3695525335470,-1717402022529,1978123312941,5.063321e+10,...,2785303975,1089337104906,-178605980097,-39011516,910692113293,0,910692113293,3695525335470,3094145678,-308841703
1,VCI,2023,2472460543397,-0.216644,491904659394,-0.433927,2472460543397,-1063597101525,1408863441872,2.369615e+10,...,128411319,570138640134,-64320454739,-13913526001,491904659394,0,491904659394,2472460543397,132390105,-3978786
2,VCI,2022,3156242736345,-0.148588,868978185802,-0.420186,3156242736345,-1398531179478,1757711556867,3.554843e+10,...,43696276107,1059738713385,-250981079495,60220551912,868978185802,0,868978185802,3156242736345,44543029091,-846752984
3,VCI,2021,3707068724492,1.143320,1498718375328,0.949141,3707068724492,-1326133822522,2380934901970,2.561687e+10,...,-267786912,1850585393088,-309748513618,-42118504142,1498718375328,0,1498718375328,3707068724492,69316632,-337103544
4,VCI,2020,1729591590563,0.122423,768912289421,0.109253,1729591590563,-522004485232,1207587105331,5.858556e+09,...,621078878,951038957081,-182422798514,296130854,768912289421,0,768912289421,1729591590563,621078878,0

In [62]:
fin.income_statement(period='quarter', lang='en', dropna=True).head()

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Net Sales,Cost of Sales,Gross Profit,...,Net other income/expenses,Profit before tax,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Minority Interest,Attributable to parent company,Sales,Other income,Other Income/Expenses
0,VCI,2024,4,998995850627,0.239917,218376745828,0.776135,998995850627,-519893652425,479102198202,...,21194452,253335115979,-35884665831,926295680,218376745828,0,218376745828,998995850627,23636364,-2441912
1,VCI,2024,3,974360554621,0.461496,215352225175,0.203064,974360554621,-468140246243,506220308378,...,0,264695399242,-40189361297,-9153812770,215352225175,0,215352225175,974360554621,0,0
2,VCI,2024,2,915851554761,0.828529,279206679897,1.388492,915851554761,-359336052126,556515502635,...,2826585413,343766121537,-64821621464,262179824,279206679897,0,279206679897,915851554761,2837985204,-11399791
3,VCI,2024,1,806317375461,0.615187,197756462393,1.706977,806317375461,-370032071735,436285303726,...,-62475890,227540468148,-37710331505,7926325750,197756462393,0,197756462393,806317375461,232524110,-295000000
4,VCI,2023,4,805695933425,0.011994,122950502675,3.324213,805695933425,-419422487555,386273445870,...,13012123,149131831394,-7570702516,-18610626203,122950502675,0,122950502675,805695933425,16990909,-3978786

### Báo cáo lưu chuyển tiền tệ

In [63]:
fin.cash_flow(period='year', dropna=True).head()

,ticker,yearReport,Net Profit/Loss before tax,Depreciation and Amortisation,Provision for credit losses,Unrealized foreign exchange gain/loss,Profit/Loss from investing activities,Interest Expense,Interest income and dividends,Operating profit before changes in working capital,...,Payments for share repurchases,Proceeds from borrowings,Repayment of borrowings,Dividends paid,Cash flows from financial activities,Net increase/decrease in cash and cash equivalents,Cash and cash equivalents,Cash and Cash Equivalents at the end of period,_Increase/Decrease in receivables,_Increase/Decrease in payables
0,VCI,2024,1089337104906,10751194638,4516800000,0,0,764124674808,-8.608679e+10,-5169139240487,...,0,28212221000000,-24737632000000,-177803580300,7371225419700,3955874113505,787897819240,4743771932745,0,65609975849
1,VCI,2023,570138640134,9679599271,11292000000,0,0,562553033255,-1.032191e+11,-5407321967895,...,0,20322010000000,-18096042142857,-522119971000,1727849074143,-2635603795563,3423501614803,787897819240,0,3923102445
2,VCI,2022,1059738713385,9647191174,0,0,154602984,477360036322,-5.948490e+10,2006811362129,...,0,15126047142857,-16579490000000,0,-1428442857143,2291753015270,1131748599533,3423501614803,0,-119194100124
3,VCI,2021,1850585393088,7496942452,-214202387,0,0,330776772616,-4.785212e+10,-5732733292320,...,0,16591566600000,-11629266600000,-730123222800,4245676777200,489235615943,642512983590,1131748599533,5939376000,88803338332
4,VCI,2020,951038957081,10634646105,-35400000,0,-500000000,173513458172,-2.094800e+10,-1673271187005,...,-852000000,7065840000000,-6233940000000,-411641446500,432858721500,-151998779012,794511762602,642512983590,57321090000,-265045502541

In [64]:
fin.income_statement(period='quarter', lang='en', dropna=True).head()

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Net Sales,Cost of Sales,Gross Profit,...,Net other income/expenses,Profit before tax,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Minority Interest,Attributable to parent company,Sales,Other income,Other Income/Expenses
0,VCI,2024,4,998995850627,0.239917,218376745828,0.776135,998995850627,-519893652425,479102198202,...,21194452,253335115979,-35884665831,926295680,218376745828,0,218376745828,998995850627,23636364,-2441912
1,VCI,2024,3,974360554621,0.461496,215352225175,0.203064,974360554621,-468140246243,506220308378,...,0,264695399242,-40189361297,-9153812770,215352225175,0,215352225175,974360554621,0,0
2,VCI,2024,2,915851554761,0.828529,279206679897,1.388492,915851554761,-359336052126,556515502635,...,2826585413,343766121537,-64821621464,262179824,279206679897,0,279206679897,915851554761,2837985204,-11399791
3,VCI,2024,1,806317375461,0.615187,197756462393,1.706977,806317375461,-370032071735,436285303726,...,-62475890,227540468148,-37710331505,7926325750,197756462393,0,197756462393,806317375461,232524110,-295000000
4,VCI,2023,4,805695933425,0.011994,122950502675,3.324213,805695933425,-419422487555,386273445870,...,13012123,149131831394,-7570702516,-18610626203,122950502675,0,122950502675,805695933425,16990909,-3978786

### Chỉ số tài chính

In [67]:
fin.ratio(period='year', lang='vi', flatten_columns=True, drop_levels=[0], dropna=True).head()

,CP,Năm,Kỳ,(Vay NH+DH)/VCSH,Nợ/VCSH,TSCĐ / Vốn CSH,Vốn CSH/Vốn điều lệ,Vòng quay tài sản,Vòng quay TSCĐ,Số ngày thu tiền bình quân,...,Đòn bẩy tài chính,P/B,Vốn hóa (đồng),Số CP lưu hành (Triệu CP),P/E,P/S,P/Cash Flow,EPS (VND),BVPS (VND),EV/EBITDA
0,VCI,2024,5,0.971382,1.054349,0.002879,1.802578,0.168564,121.775022,0.0,...,2.054349,2.052615,26569680760000,718099480,29.175262,7.189690,-7.851447,1268.197706,18025.783068,18.653217
1,VCI,2023,5,1.218152,1.340876,0.003178,1.026491,0.156992,105.385605,0.0,...,2.340876,1.970499,14525000000000,437500000,29.528080,5.874715,-3.334822,1124.353507,16848.524590,17.525975
2,VCI,2022,5,0.973942,1.192721,0.003617,0.904536,0.204426,172.225781,0.0,...,2.192721,2.866248,18617620767750,435499901,21.424727,5.898666,4.975461,1995.357941,14914.970490,12.729467
3,VCI,2021,5,0.972610,1.543047,0.002011,0.910997,0.296344,269.213152,0.0,...,2.543047,1.183493,7742250000000,333000000,5.165914,2.088510,-2.064593,4500.655782,19645.234971,5.895364
4,VCI,2020,5,0.596293,0.853905,0.003181,0.629646,0.221383,142.402909,0.0,...,1.853905,2.666309,12055680000000,165600000,15.678875,6.970247,-21.093469,4643.190154,27303.662559,12.313747

In [68]:
fin.ratio(period='quarter', lang='en', flatten_columns=True, drop_levels=[0], dropna=True).head()

,ticker,yearReport,lengthReport,(ST+LT borrowings)/Equity,Debt/Equity,Fixed Asset-To-Equity,Owners' Equity/Charter Capital,Asset Turnover,Fixed Asset Turnover,Days Sales Outstanding,...,Financial Leverage,P/B,Market Capital (Bn. VND),Outstanding Share (Mil. Shares),P/E,P/S,P/Cash Flow,EPS (VND),BVPS (VND),EV/EBITDA
0,VCI,2024,4,0.971382,1.054349,0.002879,1.802578,0.168564,121.775022,0.0,...,2.054349,2.052615,26569680760000,718099480,24.055917,7.189690,-6.473764,304.103752,18025.783068,18.902133
1,VCI,2024,3,1.253482,1.362305,0.003381,1.203462,0.174413,131.475148,0.0,...,2.362305,1.806066,22871468438000,718099480,23.303298,6.530553,-17.723150,299.891911,17635.011093,17.958349
2,VCI,2024,2,1.398891,1.608265,0.003615,1.233606,0.166335,129.528632,0.0,...,2.608265,2.379972,21083029916000,574469480,26.866048,6.599683,-4.975656,486.025263,15420.349585,17.950658
3,VCI,2024,1,1.252192,1.390102,0.002676,1.138743,0.162937,130.111085,0.0,...,2.390102,2.571899,21167010000000,441900000,33.973894,7.615216,-4.399652,447.514058,18624.368974,20.739556
4,VCI,2023,4,1.218152,1.340876,0.003178,1.026491,0.156992,105.385605,0.0,...,2.340876,3.092259,22793750000000,437500000,46.238494,9.219055,-5.222052,281.029720,16848.524590,22.946233